./calc "FUNCTION(y=7+9*x)" "SET(x=8)"
./calc "FUNCTION(y=7+9*x)" "SET(z=8)"
./calc "FUNCTION(y=9*x+7)" "SET(x=8)"
./calc "FUNCTION(d=9*x+7)" "SET(x=8)"
./calc "FUNCTION(x=9*x+7)" "SET(x=8)"
./calc "FUNCTION(y=7+9*x)" "SET(y=8)"
./calc "SET(x=8)" "FUNCTION(y=7+9*x)"
./calc "SET(x=8)" "FUNCTION(y=7-9*x)"
./calc "SET(x=8)" "FUNCTION(y=7*9*x)"
./calc "FUNCTION(y=7*x+12)" "SET(x=12)" "SET(x=4)" "SET(x=7)" "SET(x=1000)"